#pragma once
// NOTE: All rust types and shared types must be defined as empty structs.
// They get filled in elsewhere. Do *not* include the lib.rs.h
struct ArcasRustPeerConnectionObserver;
struct ArcasRTCPeerConnectionConfig;
struct ArcasRustCreateSessionDescriptionObserver;
struct ArcasRustSetSessionDescriptionObserver;
struct ArcasPeerConnectionConfig;
struct ArcasRustVideoTrackSourceCallback;
struct ArcasRustDict;
struct ArcasRustVideoEncoderFactory;
struct ArcasRustVideoEncoderSelector;
struct ArcasRustVideoEncoder;
struct ArcasEncodedImageCallbackResult;
struct ArcasVideoEncoderFactoryCodecInfo;
struct ArcasVideoEncoderFactoryCodecSupport;
struct ArcasSdpVideoFormatInit;
struct ArcasSdpVideoFormatVecInit;
struct ArcasVideoEncodingErrCode;
struct ArcasRustRTCStatsCollectorCallback;
struct ArcasCreateSessionDescriptionResult;
struct ArcasCreateICECandidateResult;
struct ArcasTransceiverInit;
struct ArcasRustEncodedImageCallbackHandler;
struct ArcasVideoEncoderLossNotification;
struct ArcasVideoEncoderInfo;
struct ArcasVideoEncoderInfoFPSAllocation;
struct ArcasRustVideoDecoderFactory;
struct ArcasRustVideoDecoder;
